[package]
name = "file-date-fixer"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.28", features = ["derive"] }
colored = "3.0.0"
filetime = "0.2.25"
regex = "1.11.1"
